### ISSUE TITLE
Where can I find the version compatible with Joomla 1.5?

### ISSUE THREAD

**Issue by romanrandom** [nocean/SEOSimple#4]
Hi, thank you for this plugin.

I'm trying to install version 2.2, 2.5 and 3.0 on Joomla 1.5 and I'm always getting the error:
"Error! Could not find a Joomla! XML setup file in the package."

Do I need version 1.0 for it to work on Joomla 1.5?

**Comment by nocean** [comment]
Hi, I've just reorganized this whole repo so that it contains all the versions for older Joomla versions as well. See [all the releases here](https://github.com/nocean/SEOSimple/releases). I can't remember if Joomla 1.7 plugins were compatible with J1.5 or not. If the J1.7 plugin doesn't work, go with the J.15 release.

**Comment by wabisabit** [comment]
Thanks a lot! I tried the 1.7 and 1.6 releases and only the 1.5 worked.
